spring:
  application:
    name: Spring Boot Admin
  boot:
    admin:
      client:
        url: http://localhost:8500
        instance:
          service-base-url: http://localhost:8500
  thymeleaf:
    check-template-location: false

server:
  port: 8500

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
